### ISSUE TITLE
Geelong Regional Libraries

### ISSUE THREAD

**Issue by wragge** [wragge/closed-glams-covid19#27]
Closed: https://www.grlc.vic.gov.au/coronavirus

All Geelong Regional Library Corporation library branches and Moblie Libraries will close on Wednesday 18 March (at the usual branch closing time) until at least Tuesday 14 April 2020,

**Comment by johanbaaij** [comment]
@wragge in my PR https://github.com/wragge/closed-glams-covid19/pull/29
