### ISSUE TITLE
QVMAG, Launceston

### ISSUE THREAD

**Issue by michaelhoney** [wragge/closed-glams-covid19#52]
Not on QVMAG website yet, but announced by the city council:
"Temporary closures for QVMAG and aquatic centre facilities
Published on 17 March 2020
The City of Launceston will temporarily close the Launceston Leisure and Aquatic Centre and Queen Victoria Museum and Art Gallery in response to the COVID-19 pandemic.
Both facilities will close to the public at the close of business today. At this stage, the duration of the closure has not been determined and the Council will review its position in two weeks' time." 
https://www.launceston.tas.gov.au/News-Media/Temporary-closures-for-QVMAG-and-aquatic-centre-facilities

**Comment by wragge** [comment]
Thanks Michael!
